platform :ios, '14.0'

target 'ZeotapTravelExplorer' do
  use_frameworks!

  # Zeotap SDK
  pod 'ZeotapCollect', '~> 1.3.10'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
